
services:
  signer-ws:
    image: ghcr.io/ufuk-cetinkaya/signer-ws:latest
    container_name: signer-ws
    networks:
    - edonusum
    ports:
    - 8083:8080
networks:
  edonusum:
    external: true